stages:
  - deps
  - simple-docker-tests

.parallel-distro-template:
  parallel:
    matrix:
      - DISTRO_NAME: "Debian Testing"
        DISTRO_CONTAINER: "debian:testing"
        PACKAGER: "apt-get install -y"
      - DISTRO_NAME: "Fedora Latest"
        DISTRO_CONTAINER: "fedora:latest"
        PACKAGER: "dnf install -y"

setup-distro-deps:
  extends: .parallel-distro-template
  stage: deps
  image: $DISTRO_CONTAINER
  variables:
    NONROOT: qa
  script:
    - echo "Running test on $DISTRO_NAME with container $DISTRO_CONTAINER"
    - uname -a
    - echo "Successfully ran on $DISTRO_NAME"
    - echo "Going to install kdevops deps"
    - |
      # Determine package file based on the distribution
      if [ "$DISTRO_CONTAINER" = "debian:testing" ]; then
        PKG_FILE=".ci.pkg.debian.testing-packages.txt"
      elif [ "$DISTRO_CONTAINER" = "fedora:latest" ]; then
        PKG_FILE=".ci.pkg.fedora.latest-packages.txt"
      else
        echo "Unknown distribution: $DISTRO_CONTAINER"
        exit 1
      fi

    - echo "Using package file: $PKG_FILE"
    - cat $PKG_FILE
    - sudo $PACKAGER $(cat $PKG_FILE | tr '\n' ' ')

make-defconfig:
  extends: .parallel-distro-template
  stage: simple-docker-tests
  image: $DISTRO_CONTAINER
  script:
    - echo "Running simple make targets on $DISTRO_NAME environment with $DISTRO_CONTAINER"
    - make defconfig-mirror
    - make mrproper
    - make menuconfig
    - make mrproper
    - make nconfig
    - make mrproper
