stages:
  - deps
  - simple-docker-tests

.parallel-distro-template:
  parallel:
    matrix:
      - DISTRO_NAME: "Debian Testing"
        DISTRO_CONTAINER: "debian:testing"
        PACKAGER: "apt-get install -y"
        PRE_INSTALL: "apt-get update && apt-get install -y sudo"
      - DISTRO_NAME: "Fedora Latest"
        DISTRO_CONTAINER: "fedora:latest"
        PACKAGER: "dnf install -y"
        PRE_INSTALL: "dnf install -y sudo"

setup-distro-deps:
  extends: .parallel-distro-template
  stage: deps
  image: $DISTRO_CONTAINER
  variables:
    NONROOT: qa
    PACKAGE_FILE: ".ci/$CI_JOB_IMAGE-packages.txt"
  script:
    - echo "Running test on $DISTRO_NAME with container $DISTRO_CONTAINER"
    - uname -a
    - echo "Successfully ran on $DISTRO_NAME"
    - echo "Going to install kdevops deps"
    - $PACKAGER $(cat $PKG_FILE | tr '\n' ' ')

make-defconfig:
  extends: .parallel-distro-template
  stage: simple-docker-tests
  image: $DISTRO_CONTAINER
  script:
    - echo "Running simple make targets on $DISTRO_NAME environment with $DISTRO_CONTAINER"
    - make defconfig-mirror
    - make mrproper
    - make menuconfig
    - make mrproper
    - make nconfig
    - make mrproper
