stages:
  - deps
  - test-libvirt

.parallel-distro-template:
  parallel:
    matrix:
      - DISTRO_NAME: "Debian Testing"
        DISTRO_CONTAINER: "debian:testing"
      - DISTRO_NAME: "Fedora Latest"
        DISTRO_CONTAINER: "fedora:latest"

setup-distro-deps:
  extends: .parallel-distro-template
  stage: deps
  script:
    - echo "Running test on $DISTRO_NAME with container $DISTRO_CONTAINER"
    - uname -a
    - echo "Successfully ran on $DISTRO_NAME"

test-distro-libvirt-bringup:
  extends: .parallel-distro-template
  stage: test-libvirt
  script:
    - echo "Running tests on $DISTRO_NAME environment with $DISTRO_CONTAINER"
