stages:
  - deps
  - simple-docker-tests

.parallel-distro-template:
  parallel:
    matrix:
      - DISTRO_NAME: "Debian Testing"
        DISTRO_CONTAINER: "debian:testing"
        PACKAGER: "apt-get install -y"
      - DISTRO_NAME: "Fedora Latest"
        DISTRO_CONTAINER: "fedora:latest"
        PACKAGER: "dnf install "

setup-distro-deps:
  extends: .parallel-distro-template
  stage: deps
  image: $DISTRO_CONTAINER
  variables:
    NONROOT: qa
  script:
    - echo "Running test on $DISTRO_NAME with container $DISTRO_CONTAINER"
    - uname -a
    - echo "Successfully ran on $DISTRO_NAME"
    - echo "Going to install kdevops deps"
    - echo "Package file: .ci/$DISTRO_CONTAINER-packages.txt"
    - echo "Packages:"
    - echo $(cat .ci/$DISTRO_CONTAINER-packages.txt | tr '\n' ' ')
    - $PACKAGER $(cat .ci/$DISTRO_CONTAINER-packages.txt | tr '\n' ' ')

make-defconfig:
  extends: .parallel-distro-template
  stage: simple-docker-tests
  image: $DISTRO_CONTAINER
  script:
    - echo "Running simple make targets on $DISTRO_NAME environment with $DISTRO_CONTAINER"
    - make defconfig-mirror
    - make mrproper
    - make menuconfig
    - make mrproper
    - make nconfig
    - make mrproper
